# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/" # Location of package manifests
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
      timezone: Europe/Berlin
    assignees:
      - "Rindula"
    open-pull-requests-limit: 100
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "ci"
      include: "scope"
    schedule:
      interval: "daily"
      timezone: Europe/Berlin
  - package-ecosystem: gitsubmodule
    directory: /
    commit-message:
      include: scope
      prefix: "chore"
    schedule:
      interval: "daily"
      timezone: Europe/Berlin
