# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/" # Location of package manifests
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    schedule:
      interval: "weekly"
      timezone: Europe/Berlin
      time: "04:00"
      day: "sunday"
    assignees:
      - "Rindula"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      timezone: Europe/Berlin
      time: "04:00"
      day: "sunday"
    assignees:
      - "Rindula"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Europe/Berlin
      time: "04:00"
      day: "sunday"
    assignees:
      - "Rindula"
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: "weekly"
      timezone: Europe/Berlin
      time: "04:00"
      day: "sunday"
    assignees:
      - "Rindula"
