vue:
  - webroot/vue-apps/**/*

cake:
  - src/**/*
  - config/**/*
  - templates/**/*
  - resources/**/*
  - plugins/**/*

tests:
  - tests/**/*
  
workflow:
  - .github/workflows/*
  
deployscript:
  - gogogo.sh

docs:
  - README.md
  
wontfix:
  - bin/*
  - .htaccess
  - webroot/.htaccess
