symfony:
  - src/**/*
  - config/**/*
  - public/**/*
  - assets/**/*
  - templates/**/*

database:
  - migrations/**/*.php

tests:
  - tests/**/*
  
github_actions:
  - .github/workflows/*
  
workflow-config:
  - .github/*.yml

documentation:
  - README.md
  
wontfix:
  - bin/*
  - .htaccess
  - public/.htaccess
