symfony:
- changed-files:
  - any-glob-to-any-file: src/**/*
  - any-glob-to-any-file: config/**/*
  - any-glob-to-any-file: public/**/*
  - any-glob-to-any-file: assets/**/*
  - any-glob-to-any-file: templates/**/*

database:
- changed-files:
  - any-glob-to-any-file: migrations/**/*.php

tests:
- changed-files:
  - any-glob-to-any-file: tests/**/*
  
github_actions:
- changed-files:
  - any-glob-to-any-file: .github/workflows/*
  
workflow-config:
- changed-files:
  - any-glob-to-any-file: .github/*.yml

documentation:
- changed-files:
  - any-glob-to-any-file: README.md
  
executables:
- changed-files:
  - any-glob-to-any-file: bin/*

chore:
- changed-files:
  - any-glob-to-any-file: makefile
  - any-glob-to-any-file: .htaccess
  - any-glob-to-any-file: public/.htaccess

translations:
- changed-files:
  - any-glob-to-any-file: translations/**/*
