cake:
  - src/**/*
  - config/**/*
  - templates/**/*
  - resources/**/*
  - plugins/**/*

tests:
  - tests/**/*
  
github_actions:
  - .github/workflows/*
  
workflow-config:
  - .github/*.yml
  
deployscript:
  - gogogo.sh

docs:
  - README.md
  
wontfix:
  - bin/*
  - .htaccess
  - webroot/.htaccess
