vue:
  - /webroot/vue-apps/**/*

cake:
  - /src/**/*
  - /templates/**/*
  - /resources/**/*
  - /plugins/**/*

tests:
  - /tests/**/*
  
workflow:
  - /.github/workflows/*
  
deployscript:
  - /gogogo.sh
