name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🏗️ Dependencies'
    label: 'dependencies'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'deployscript'
      - 'database'
  - title: '👾 CI/CD'
    labels: 
      - 'github_actions'
      - 'workflow-config'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'database'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What’s Changed

  $CHANGES
