name: auto-merge

on:
  pull_request_target:
    types:
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.mytoken }}"
      - uses: reitermarkus/automerge@v1.5.2
        with:
          token: "${{ secrets.mytoken }}"
          pull-request: ${{ github.event.number }}
          squash-title: true
          dry-run: false
