name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: self-hosted
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.mytoken }}
          approve: false
          target: minor
