name: Auto Assign to Project(s)

on:
  issues:
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues and pull requests with `bug` label to project 2
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: |
        contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/Rindula/hirsch/projects/2'
        column_name: 'Needs triage'
