name: auto-merge

on:
  schedule:
    - cron: 0 * * * *

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1.5.2
        with:
          token: "${{ secrets.mytoken }}"
          pull-request: ${{ github.event.number }}
          squash-title: true
          merge-method: rebase
          dry-run: false
          do-not-merge-labels: wontfix
