name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        if: github.event.issue.user.login == "dependabot[bot]"
        with:
          github-token: ${{ github.token }}
