name: CI/CD
on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
    types: [synchronize, opened, reopened, ready_for_review]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: webroot/scss/style.scss
          destination: webroot/css/style.css
      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          directory: 'webroot/js'
      - name: Push Compiled Files
        uses: EndBug/add-and-commit@v7.4.0
        id: commit_step
        with:
          default_author: github_actor
          message: 'build(gh-action): compiled & minified files'
          add: "webroot/css webroot/js"
