name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: self-hosted
    strategy:
      matrix:
        php: [7.2]
    env:
      ACTION_PHP_EXTENSIONS: php${{ matrix.php }}-imap php${{ matrix.php }}-zip php${{ matrix.php }}-intl php${{ matrix.php }}-mbstring
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer dependencies
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php }}
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - working-directory: webroot/vue-apps/bezahlen
        name: Vue - Bezahlen - Abhängigkeiten installieren
        run: npm ci
      - working-directory: webroot/vue-apps/bezahlen
        name: Vue - Bezahlen - Bauen
        run: npm run build
      - name: Config anpassen
        run: |
          sed -i 's/db\_user/hirsch/' config/app_local.php
          sed -i 's/db\_pass/${{ secrets.DBPASS }}/' config/app_local.php
          sed -i 's/db\_name/hirsch/' config/app_local.php
          sed -i 's/foodwars/${{ secrets.EMAILPASS }}/' config/app_local.php
          sed -i 's/essen@rindula\.de/essen@hochwarth-e.com/' config/app_local.php
          sed -i 's/{rindula\.de\/imap\/novalidate-cert}INBOX/{sslin.df.eu\/imap}INBOX/' config/app_local.php
      - name: Passwortschutz erstellen
        run: |
          echo '' >> webroot/.htaccess
          echo 'AuthType Basic' >> webroot/.htaccess
          echo 'AuthName "Bestellungen"' >> webroot/.htaccess
          echo 'AuthUserFile /usr/www/users/hochwa/hirsch/.htpasswd' >> webroot/.htaccess
          echo 'Require valid-user' >> webroot/.htaccess
          echo 'hirsch:$1$fYrmJTqu$/RcIe9S9iVjc4l9KIJG1G.' > .htpasswd
  deploy_hetzner:
    name: Deploy (Hetzner)
    runs-on: self-hosted
    needs: build
    environment: hetzner
    steps:
      - run: sshpass -p '${{ secrets.PASSWORD }}' rsync --exclude ".git" -e "ssh -o StrictHostKeyChecking=no -p 222" -rltzvOP --del --force ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/usr/home/hochwa/public_html/hirsch
        id: upload
      - run: sshpass -p '${{ secrets.PASSWORD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p 222 -f "cd /usr/home/hochwa/public_html/hirsch && bin/cake migrations migrate && bin/cake cache clear_all"
        id: preperations
