name: PHP Check

on:
  pull_request:
    branches: [ master ]

jobs:
    test:
        name: Unittest
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            matrix:
                php: [ 8 ]
                experimental: [ false ]
                include:
                    -   php: 7.4
                        experimental: true
        services:
            mariadb:
                image: mariadb:10.6.4
                ports:
                    - 3306
                env:
                    MYSQL_USER: hirsch
                    MYSQL_PASSWORD: testing
                    MYSQL_DATABASE: hirsch_test
                    MYSQL_ROOT_PASSWORD: root
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        steps:
            -   uses: actions/checkout@v2.4.0

            -   uses: shivammathur/setup-php@2.15.0
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
                    extensions: intl, mbstring, imap, zip, dom, pdo_mysql

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Replace variables
                env:
                    DB_PORT: ${{ job.services.mariadb.ports[3306] }}
                run: |
                    echo "DATABASE_URL="mysql://hirsch:testing@hirsch_test:${DB_PORT}/db?serverVersion=mariadb-10.6.4" >> .env.local


            # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
            # Docs: https://getcomposer.org/doc/articles/scripts.md

            -   name: Run Unittests
                run: composer run-script test
