name: PHP Check

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unittest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run Unittests
      run: composer run-script test
