name: PHP Check

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unittest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        tools: composer:v2
        extensions: intl, mbstring, imap, zip, dom, pdo_mysql

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run Unittests
      run: composer run-script test
