name: PHP Check

on:
  workflow_call:
  pull_request:
    branches: [ master ]

jobs:
  stan:
    name: PHP Stan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@2.17.1
        with:
          php-version: 8
          tools: composer:v2
          extensions: intl, mbstring, imap, zip, dom, pdo_mysql
      - name: Dependencies
        run: make vendor
      - name: PHP Stan Analyse
        run: vendor/bin/phpstan analyse
  coverage:
    name: PHP Code Coverage
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.6.4
        ports:
          - 3306
        env:
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_DATABASE: db_test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ssh-key: '${{ secrets.SSHKEY }}'
          lfs: true
      - uses: shivammathur/setup-php@2.17.1
        with:
          php-version: 8
          tools: composer:v2
          extensions: intl, mbstring, imap, zip, dom, pdo_mysql
      - name: Replace variables
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          echo "DATABASE_URL=mysql://db:db@127.0.0.1:${DB_PORT}/db?serverVersion=mariadb-10.6.4" >> .env.test.local
          echo "APP_VERSION=${GITHUB_REF/refs\/tags\//}" >> .env.test.local
      - name: Dependencies
        run: make install_deps
      - run: make coverage_check
      - uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: coverage
          path: coverage-html
  infection:
    name: PHP Infection Test
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.6.4
        ports:
          - 3306
        env:
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_DATABASE: db_test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ssh-key: '${{ secrets.SSHKEY }}'
          lfs: true
      - uses: shivammathur/setup-php@2.17.0
        with:
          php-version: 8
          tools: composer:v2
          extensions: intl, mbstring, imap, zip, dom, pdo_mysql
      - name: Replace variables
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          echo "DATABASE_URL=mysql://db:db@127.0.0.1:${DB_PORT}/db?serverVersion=mariadb-10.6.4" >> .env.test.local
          echo "APP_VERSION=${GITHUB_REF/refs\/tags\//}" >> .env.test.local
      - name: Dependencies
        run: make install_deps
      - run: make infection_test
      - uses: actions/upload-artifact@master
        if: ${{ failure() }}
        with:
          name: infection_log
          path: infection.log
  test:
    name: Unittest
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php: [8, 8.1]
        experimental: [false]
        # include:
          # includes a new variable of npm with a value of 6
          # for the matrix leg matching the os and version
          # - php: 8.2
          #   experimental: true
    services:
      mariadb:
        image: mariadb:10.6.4
        ports:
          - 3306
        env:
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_DATABASE: db_test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '15'
      - uses: shivammathur/setup-php@2.17.1
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: intl, mbstring, imap, zip, dom, pdo_mysql

      - name: Replace variables
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          echo "DATABASE_URL=mysql://db:db@127.0.0.1:${DB_PORT}/db?serverVersion=mariadb-10.6.4" >> .env.test.local
      - run: make install
        name: Install dependencies
        env:
          APP_ENV: test
      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run Unittests
        run: bin/phpunit
        env:
          APP_ENV: test
