name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN:  ${{ github.token }}
