name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ github.token }}
          create_annotated_tag: true
