name: "Todo to Issue"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.4.0"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.6"
        id: "todo"
